name: Build and Publish
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Gatsby
        run: npm install -g gatsby
      - name: Run `npm install`
        run: npm install
      - name: Build the website
        run: gatsby build
      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: built-website
          path: public
          retention-days: 1

  Publish:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v3
        with:
          name: built-website
      - name: List public folder
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ls public/
      - name: List S3 path
        run: aws ls s3://caius.brindescu.com/
      # - name: Install AWS CLI
      #   run: apt install awscli
      # - name: Upload to S3
      #   run: aws s3 public s3://caius.brindescu.com/ --delete --dryrun
      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id E3PS86HUMZ47EU --paths '*'