name: Build and Publish
run-name: ${{ github.actor }} is building new changes
on: [push]]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Run `npm install`
        run: npm install
      - name: Build the website
        run: gatsby build