name: Build and Publish
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Gatsby
        run: npm install -g gatsby
      - name: Run `npm install`
        run: npm install
      - name: Build the website
        run: gatsby build